# Generated by Django 4.2.1 on 2023-05-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='settings',
            new_name='settings',
        ),
    ]
